client_config_backend: settings
client_config:
  client_id: 152678138581-4hvu45rcoq6n9jvjnofl49i8ci6mh5jd.apps.googleusercontent.com
  client_secret: ckO_0_DPa8Cukw93coo1DNCi

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials/credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.appdata
